// Code generated by SQLBoiler 4.10.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"strconv"
	"time"

	"github.com/Beep-Technologies/beepbeep3-ocpp/pkg/constants"
)

// UserTransaction is an object representing the database table.
type UserTransaction struct {
	ID            int32     `gorm:"column:id"`
	UserID        int32     `gorm:"column:user_id"`
	TransactionID int32     `gorm:"column:transaction_id"`
	CreatedAt     time.Time `gorm:"column:created_at"`
}

func (UserTransaction) TableName() string {
	_ = strconv.Quote("")
	return constants.SCHEMA + "user_transaction"
}
